/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package org.eclipse.epsilon.cbp.resource.thrift.structs;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class TRegisterEPackageEvent implements org.apache.thrift.TBase<TRegisterEPackageEvent, TRegisterEPackageEvent._Fields>, java.io.Serializable, Cloneable, Comparable<TRegisterEPackageEvent> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("TRegisterEPackageEvent");

  private static final org.apache.thrift.protocol.TField E_PACKAGE_FIELD_DESC = new org.apache.thrift.protocol.TField("ePackage", org.apache.thrift.protocol.TType.STRING, (short)1);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new TRegisterEPackageEventStandardSchemeFactory());
    schemes.put(TupleScheme.class, new TRegisterEPackageEventTupleSchemeFactory());
  }

  public String ePackage; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    E_PACKAGE((short)1, "ePackage");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // E_PACKAGE
          return E_PACKAGE;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.E_PACKAGE, new org.apache.thrift.meta_data.FieldMetaData("ePackage", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(TRegisterEPackageEvent.class, metaDataMap);
  }

  public TRegisterEPackageEvent() {
  }

  public TRegisterEPackageEvent(
    String ePackage)
  {
    this();
    this.ePackage = ePackage;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public TRegisterEPackageEvent(TRegisterEPackageEvent other) {
    if (other.isSetEPackage()) {
      this.ePackage = other.ePackage;
    }
  }

  public TRegisterEPackageEvent deepCopy() {
    return new TRegisterEPackageEvent(this);
  }

  @Override
  public void clear() {
    this.ePackage = null;
  }

  public String getEPackage() {
    return this.ePackage;
  }

  public TRegisterEPackageEvent setEPackage(String ePackage) {
    this.ePackage = ePackage;
    return this;
  }

  public void unsetEPackage() {
    this.ePackage = null;
  }

  /** Returns true if field ePackage is set (has been assigned a value) and false otherwise */
  public boolean isSetEPackage() {
    return this.ePackage != null;
  }

  public void setEPackageIsSet(boolean value) {
    if (!value) {
      this.ePackage = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case E_PACKAGE:
      if (value == null) {
        unsetEPackage();
      } else {
        setEPackage((String)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case E_PACKAGE:
      return getEPackage();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case E_PACKAGE:
      return isSetEPackage();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof TRegisterEPackageEvent)
      return this.equals((TRegisterEPackageEvent)that);
    return false;
  }

  public boolean equals(TRegisterEPackageEvent that) {
    if (that == null)
      return false;

    boolean this_present_ePackage = true && this.isSetEPackage();
    boolean that_present_ePackage = true && that.isSetEPackage();
    if (this_present_ePackage || that_present_ePackage) {
      if (!(this_present_ePackage && that_present_ePackage))
        return false;
      if (!this.ePackage.equals(that.ePackage))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  @Override
  public int compareTo(TRegisterEPackageEvent other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetEPackage()).compareTo(other.isSetEPackage());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetEPackage()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.ePackage, other.ePackage);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("TRegisterEPackageEvent(");
    boolean first = true;

    sb.append("ePackage:");
    if (this.ePackage == null) {
      sb.append("null");
    } else {
      sb.append(this.ePackage);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    if (ePackage == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'ePackage' was not present! Struct: " + toString());
    }
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class TRegisterEPackageEventStandardSchemeFactory implements SchemeFactory {
    public TRegisterEPackageEventStandardScheme getScheme() {
      return new TRegisterEPackageEventStandardScheme();
    }
  }

  private static class TRegisterEPackageEventStandardScheme extends StandardScheme<TRegisterEPackageEvent> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, TRegisterEPackageEvent struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // E_PACKAGE
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.ePackage = iprot.readString();
              struct.setEPackageIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, TRegisterEPackageEvent struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.ePackage != null) {
        oprot.writeFieldBegin(E_PACKAGE_FIELD_DESC);
        oprot.writeString(struct.ePackage);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class TRegisterEPackageEventTupleSchemeFactory implements SchemeFactory {
    public TRegisterEPackageEventTupleScheme getScheme() {
      return new TRegisterEPackageEventTupleScheme();
    }
  }

  private static class TRegisterEPackageEventTupleScheme extends TupleScheme<TRegisterEPackageEvent> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, TRegisterEPackageEvent struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      oprot.writeString(struct.ePackage);
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, TRegisterEPackageEvent struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      struct.ePackage = iprot.readString();
      struct.setEPackageIsSet(true);
    }
  }

}

