<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="cbp" nsURI="cbp" nsPrefix="">
  <eAnnotations source="thrift">
    <details key="javans" value="org.eclipse.epsilon.cbp.resource.thrift.structs"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="TChangeEvent">
    <eAnnotations source="doc">
      <details key="d" value="All the event types available for CBP."/>
    </eAnnotations>
    <eAnnotations source="thrift">
      <details key="union" value="true"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="createEObject" eType="#//TCreateEObjectEvent"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="addToEAttribute" eType="#//TAddToEAttributeEvent"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="setEAttribute" eType="#//TSetEAttributeEvent"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="moveWithinEAttribute" eType="#//TMoveWithinEAttributeEvent"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="removeFromEAttribute" eType="#//TRemoveFromEAttributeEvent"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="unsetEAttribute" eType="#//TUnsetEAttributeEvent"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="addToEReference" eType="#//TAddToEReferenceEvent"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="moveWithinEReference" eType="#//TMoveWithinEReferenceEvent"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="removeFromEReference" eType="#//TRemoveFromEReferenceEvent"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="setEReference" eType="#//TSetEReferenceEvent"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="unsetEReference" eType="#//TUnsetEReferenceEvent"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="registerEPackage" eType="#//TRegisterEPackageEvent"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="addToResource" eType="#//TAddToResourceEvent"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="removeFromResource" eType="#//TRemoveFromResourceEvent"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TCreateEObjectEvent">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ePackage" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eClass" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MoveEvent" abstract="true">
    <eAnnotations source="doc">
      <details key="exclude" value="true"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fromPosition" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="toPosition" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EStructuralFeatureEvent" abstract="true">
    <eAnnotations source="doc">
      <details key="exclude" value="true"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LiteralValueEvent" abstract="true">
    <eAnnotations source="doc">
      <details key="exclude" value="true"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="values" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="position" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EObjectValueEvent" abstract="true">
    <eAnnotations source="doc">
      <details key="exclude" value="true"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ids" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="xrefs" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="position" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TAddToEAttributeEvent" eSuperTypes="#//EStructuralFeatureEvent #//LiteralValueEvent"/>
  <eClassifiers xsi:type="ecore:EClass" name="TMoveWithinEAttributeEvent" eSuperTypes="#//EStructuralFeatureEvent #//MoveEvent"/>
  <eClassifiers xsi:type="ecore:EClass" name="TRemoveFromEAttributeEvent" eSuperTypes="#//EStructuralFeatureEvent #//LiteralValueEvent"/>
  <eClassifiers xsi:type="ecore:EClass" name="TSetEAttributeEvent" eSuperTypes="#//EStructuralFeatureEvent #//LiteralValueEvent"/>
  <eClassifiers xsi:type="ecore:EClass" name="TUnsetEAttributeEvent" eSuperTypes="#//EStructuralFeatureEvent"/>
  <eClassifiers xsi:type="ecore:EClass" name="TAddToEReferenceEvent" eSuperTypes="#//EStructuralFeatureEvent #//EObjectValueEvent"/>
  <eClassifiers xsi:type="ecore:EClass" name="TMoveWithinEReferenceEvent" eSuperTypes="#//EStructuralFeatureEvent #//MoveEvent"/>
  <eClassifiers xsi:type="ecore:EClass" name="TRemoveFromEReferenceEvent" eSuperTypes="#//EStructuralFeatureEvent #//EObjectValueEvent"/>
  <eClassifiers xsi:type="ecore:EClass" name="TSetEReferenceEvent" eSuperTypes="#//EStructuralFeatureEvent #//EObjectValueEvent"/>
  <eClassifiers xsi:type="ecore:EClass" name="TUnsetEReferenceEvent" eSuperTypes="#//EStructuralFeatureEvent"/>
  <eClassifiers xsi:type="ecore:EClass" name="TRegisterEPackageEvent">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ePackage" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ResourceEvent" abstract="true" eSuperTypes="#//EObjectValueEvent">
    <eAnnotations source="doc">
      <details key="exclude" value="true"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TAddToResourceEvent" eSuperTypes="#//ResourceEvent"/>
  <eClassifiers xsi:type="ecore:EClass" name="TRemoveFromResourceEvent" eSuperTypes="#//ResourceEvent"/>
</ecore:EPackage>
